version: '3'
services:
  backend:
    build:
      context: '.'
      dockerfile: GigaComic/Dockerfile
    ports:
      - "8081:3000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Stage
      - ASPNETCORE_URLS=http://+:3000

  frontend:
    build:
      context: '.'
      dockerfile: GigaComic.Client/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Stage
      - ASPNETCORE_URLS=https://+:443;http://+:80