version: '3.8'
services:
  backend:
    build:
      context: '.'
      dockerfile: GigaComic/Dockerfile
    ports:
      - "8081:3000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Stage
      - ASPNETCORE_URLS=http://+:3000

  frontend:
    build:
      context: '.'
      dockerfile: GigaComic.Client/Dockerfile
    ports:
      - "8082:3000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Stage
      - ASPNETCORE_URLS=http://+:3000