version: '3'
services:
  backend:
    build: 
      context: '.'
      dockerfile: 'GigaComic/Dockerfile'
    ports:
      - "1300:3000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:3000
  frontend:
    build: 
      context: '.'
      dockerfile: 'GigaComic.Client/Dockerfile'
    ports:
      - "1400:3000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:3000